<a href="https://colab.research.google.com/github/joelAno225/GoMyCode/blob/main/checkpoint2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Question1

In [4]:
#Écrivez un programme qui trouvera tous les nombres divisibles par 7 mais non multiples de 5,
#entre 2000 et 3200 (les deux inclus). Les nombres obtenus doivent être imprimés dans une liste.
#en utilisant la méthode range().

list([i for i in range(2000, 3201) if i % 7 == 0 if i % 5 != 0] )
#la liste s"affiche en horizontale 

[2002,
 2009,
 2016,
 2023,
 2037,
 2044,
 2051,
 2058,
 2072,
 2079,
 2086,
 2093,
 2107,
 2114,
 2121,
 2128,
 2142,
 2149,
 2156,
 2163,
 2177,
 2184,
 2191,
 2198,
 2212,
 2219,
 2226,
 2233,
 2247,
 2254,
 2261,
 2268,
 2282,
 2289,
 2296,
 2303,
 2317,
 2324,
 2331,
 2338,
 2352,
 2359,
 2366,
 2373,
 2387,
 2394,
 2401,
 2408,
 2422,
 2429,
 2436,
 2443,
 2457,
 2464,
 2471,
 2478,
 2492,
 2499,
 2506,
 2513,
 2527,
 2534,
 2541,
 2548,
 2562,
 2569,
 2576,
 2583,
 2597,
 2604,
 2611,
 2618,
 2632,
 2639,
 2646,
 2653,
 2667,
 2674,
 2681,
 2688,
 2702,
 2709,
 2716,
 2723,
 2737,
 2744,
 2751,
 2758,
 2772,
 2779,
 2786,
 2793,
 2807,
 2814,
 2821,
 2828,
 2842,
 2849,
 2856,
 2863,
 2877,
 2884,
 2891,
 2898,
 2912,
 2919,
 2926,
 2933,
 2947,
 2954,
 2961,
 2968,
 2982,
 2989,
 2996,
 3003,
 3017,
 3024,
 3031,
 3038,
 3052,
 3059,
 3066,
 3073,
 3087,
 3094,
 3101,
 3108,
 3122,
 3129,
 3136,
 3143,
 3157,
 3164,
 3171,
 3178,
 3192,
 3199]

#Question2

In [ ]:
#Programe pour calculer le factoriel de n'inporte quel nombre

def factoriel(n):
  if n == 0:
    return 1
  else :
    return n*factoriel(n-1)  
x = int(input("Entrer la valeur de x :"))   
y = factoriel(x)
print("{}!= {}".format(x,y))   

Entrer la valeur de x :5
5!= 120


#Question3

In [ ]:
#Avec un nombre entier n donné, écrivez un programme pour générer un dictionnaire qui contient 
#(i, i*i) tel qu'il soit un nombre entier compris entre 1 et n (tous deux inclus). 
#puis le programme doit imprimer le dictionnaire. Supposons que l'entrée suivante soit fournie 
#au programme : 8 Ensuite, la sortie doit être : {1 : 1, 2 : 4, 3 : 9, 4 : 16, 5 : 25, 6 : 36, 7 : 49, 8 : 64 }

nbr_n = int(input("Entrer un nombre: "))

nbr_n_Dict = {}
for i in range(1, nbr_n+1):
    nbr_n_Dict[i] = i*i

print(nbr_n_Dict)

Entrer un nombre: 2
{1: 1, 2: 4}


#Question4

In [7]:
#Étant donné une chaîne non vide et un int n, renvoie une nouvelle chaîne où le caractère à l'index n a été supprimé.
# La valeur de n sera un index valide d'un caractère dans la chaîne d'origine 
#(c'est-à-dire que n sera compris entre 0..len(str)-1 inclus).
#missing_char('kitten', 1) → 'ktten' par exemple ici on supprime "i" qui se trouve dans l'index 1
#missing_char('kitten', 0) → 'itten' ici on supprime "k" qui est dans l'index 0
#missing_char('kitten', 4) → 'kittn' ici on supprime "e" qui est dans l'index 4

def missing_char(str, n):
      first_part = str[:n] 
      last_part = str[n+1:]
      return first_part + last_part
print(missing_char('kitten', 1))
print(missing_char('kitten', 0))
print(missing_char('kitten', 4))

ktten
itten
kittn


#Question5

In [14]:
#Écrivez un programme NumPy pour convertir un tableau NumPy en une structure de liste Python
#Production attendue: Éléments du tableau d'origine : [[0 1] [2 3] [4 5]]
#Tableau à liste : [[0, 1], [2, 3], [4, 5]]
#Astuce : on peut utiliser la fonction to_list() pour assurer la conversion.

import numpy as np

x= np.array([[0, 1], [2, 3], [4, 5]])
x.tolist()

[[0, 1], [2, 3], [4, 5]]

#Question6

In [19]:
#Écrivez un programme NumPy pour calculer la matrice de covariance de deux tableaux donnés.
#Tableau d'origine1 : [0 1 2]
#Tableau d'origine2 : [2 1 0]
#Matrice de covariance desdits tableaux : [[ 1. -1.] [-1. 1.]]

import numpy as np
a= np.array([1, 2 ,3])
b= np.array([1, 2 ,3])
print("\n Tableau 1")
print(a)
print("\n Tableau 2")
print(b)
#calcule de coovariance 
print("\n la cov(a,b) est; \n",np.cov(a,b))


 Tableau 1
[1 2 3]

 Tableau 2
[1 2 3]

 la cov(a,b) est; 
 [[1. 1.]
 [1. 1.]]


#Question7

In [25]:
#Question : Écrivez un programme qui calcule et imprime la valeur selon la formule donnée : Q = Racine carrée de [(2 * C * D)/H]

#Voici les valeurs fixes de C et H : C est 50. H est 30.D est la variable dont les valeurs doivent être entrées 

#dans votre programme dans une séquence séparée par des virgules. (cela signifie que D contient plus que la valeur)

#Exemple Supposons que la séquence d'entrée suivante séparée par des virgules est donnée au programme : 100,150,180 
#La sortie du programme doit être : 18,22,24

#Pour expliquer cela plus en détail, nous obtiendrons un résultat pour chaque valeur de D : 
#Q1= Racine carrée de [(2 * C * 100)/H] =18, Q2= Racine carrée de [(2 * C * 150)/H ] = 22 et Q3 = Racine carrée de [(2 * C * 180)/H] = 24
#Conseils : Si la sortie reçue est sous forme décimale, 
#elle doit être arrondie à sa valeur la plus proche (par exemple, si la sortie reçue est 26,0, elle doit être imprimée sous la forme 26) En cas de données d'entrée fournies à la question, il doit être supposé être une entrée de console.

import math

C=50
H=30
value = []
items=[x for x in input().split(',')]
for D in items:
   Q = value.append(str(int(round(math.sqrt(2*C*float(D)/H)))))
print (','.join(value))

200,50,69
26,13,15
